os: linux
  
language: go

go:
  - 1.13.x

services:
- docker

script:   
  # Test the code
  - go test -v ./...
  # Build the code 
  - CGO_ENABLED=0 GOARCH=amd64 go build -o demo
  
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  
  - docker build -f Dockerfile -t jbraeuer/demo:latest ./
  
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag jbraeuer/demo:latest jbraeuer/demo:$GIT_SHA
  
  - docker push jbraeuer/demo:latest
  - docker push jbraeuer/demo:$GIT_SHA
  
